"""Runtime adapters for the core research state kernel."""

from .codec import (
    run_from_dict,
    run_from_json,
    run_to_dict,
    run_to_json,
)
from .commands import (
    BlockingGapSpec,
    CommandRejectedError,
    CompletionSubmissionConflictError,
    CompletionSubmissionResult,
    CreateRunRequest,
    CreateRunResult,
    NewBlockingGap,
    PaperSearchHit,
    PutLandscapeFinding,
    PutPaperAnalysis,
    ReopenBlockingGap,
    RequestCompletionCheckResult,
    ResearchCommands,
    ResearchMutationBatch,
    ResearchMutationResult,
    ResearchPut,
    RetainPapersResult,
)
from .persistence import (
    JsonResearchRunRepository,
    RevisionConflictError,
    RunAlreadyExistsError,
    RunNotFoundError,
)

__all__ = [
    "BlockingGapSpec",
    "CommandRejectedError",
    "CompletionSubmissionConflictError",
    "CompletionSubmissionResult",
    "CreateRunRequest",
    "CreateRunResult",
    "JsonResearchRunRepository",
    "NewBlockingGap",
    "PaperSearchHit",
    "PutLandscapeFinding",
    "PutPaperAnalysis",
    "ReopenBlockingGap",
    "RequestCompletionCheckResult",
    "ResearchCommands",
    "ResearchMutationBatch",
    "ResearchMutationResult",
    "ResearchPut",
    "RevisionConflictError",
    "RunAlreadyExistsError",
    "RunNotFoundError",
    "RetainPapersResult",
    "run_from_dict",
    "run_from_json",
    "run_to_dict",
    "run_to_json",
]
