"""Runtime adapters for the core research state kernel."""

from .codec import (
    delivery_basis_from_dict,
    delivery_basis_to_dict,
    run_from_dict,
    run_from_json,
    run_to_dict,
    run_to_json,
)
from .artifacts import (
    ArtifactValidationError,
    LocalArtifactStore,
    ReportArtifact,
    ReportArtifactMetadata,
)
from .commands import (
    BlockingGapSpec,
    CommandRejectedError,
    CompletionSubmissionConflictError,
    CompletionSubmissionResult,
    CreateRunRequest,
    CreateRunResult,
    NewBlockingGap,
    PutLandscapeFinding,
    PutPaperAnalysis,
    ReopenBlockingGap,
    RequestCompletionCheckResult,
    ResearchCommands,
    ResearchMutationBatch,
    ResearchMutationResult,
    ResearchPut,
    RetainPapersResult,
)
from .deepxiv import DeepXivPaperSearchProvider
from .paper_search import (
    PaperSearchAttemptError,
    PaperSearchConfigurationError,
    PaperSearchHit,
    PaperSearchProvider,
    PaperSearchProviderError,
    PaperSearchRejectedError,
    PaperSearchResult,
    PaperSearchService,
    ProviderFailureKind,
)
from .persistence import (
    JsonResearchRunRepository,
    RevisionConflictError,
    RunAlreadyExistsError,
    RunNotFoundError,
)
from .delivery import (
    CloseRunResult,
    DeliveryCommands,
    DeliveryValidationResult,
    PublishReportResult,
    ReopenResearchResult,
)

__all__ = [
    "BlockingGapSpec",
    "ArtifactValidationError",
    "CloseRunResult",
    "CommandRejectedError",
    "CompletionSubmissionConflictError",
    "CompletionSubmissionResult",
    "CreateRunRequest",
    "CreateRunResult",
    "DeliveryCommands",
    "DeliveryValidationResult",
    "DeepXivPaperSearchProvider",
    "JsonResearchRunRepository",
    "LocalArtifactStore",
    "NewBlockingGap",
    "PaperSearchHit",
    "PaperSearchAttemptError",
    "PaperSearchConfigurationError",
    "PaperSearchProvider",
    "PaperSearchProviderError",
    "PaperSearchRejectedError",
    "PaperSearchResult",
    "PaperSearchService",
    "ProviderFailureKind",
    "PutLandscapeFinding",
    "PutPaperAnalysis",
    "PublishReportResult",
    "ReopenBlockingGap",
    "RequestCompletionCheckResult",
    "ResearchCommands",
    "ResearchMutationBatch",
    "ResearchMutationResult",
    "ResearchPut",
    "ReopenResearchResult",
    "ReportArtifact",
    "ReportArtifactMetadata",
    "RevisionConflictError",
    "RunAlreadyExistsError",
    "RunNotFoundError",
    "RetainPapersResult",
    "delivery_basis_from_dict",
    "delivery_basis_to_dict",
    "run_from_dict",
    "run_from_json",
    "run_to_dict",
    "run_to_json",
]
